data <- read.csv("../results/cls_slrrates_2015.csv")

print("satellite - length")
print(sum(data$sat_length)/sum(data$length))
print("satellite - pop")
print(sum(data$sat_pop)/sum(data$pop_below_10p0))
print("uplift - length")
print(sum(data$uplift_length)/sum(data$length))
print("uplift - pop")
print(sum(data$uplift_pop)/sum(data$pop_below_10p0))
print("delta - length")
print(sum(data$deltasubsidence_length)/sum(data$length))
print("delta - pop")
print(sum(data$deltasubsidence_pop)/sum(data$pop_below_10p0))
print("city (high) - length")
print(sum(data$citysubsidence_uncontrolled_high_length)/sum(data$length))
print("city (high) - pop")
print(sum(data$citysubsidence_uncontrolled_high_pop)/sum(data$pop_below_10p0))
print("city (low) - length")
print(sum(data$citysubsidence_uncontrolled_low_length)/sum(data$length))
print("city (low) - pop")
print(sum(data$citysubsidence_uncontrolled_low_pop)/sum(data$pop_below_10p0))

table1 <- data.frame (
    t(c((sum(data$sat_length)/sum(data$length)),(sum(data$sat_pop)/sum(data$pop_below_10p0)),(sum(data$uplift_length)/sum(data$length)),(sum(data$uplift_pop)/sum(data$pop_below_10p0)),(sum(data$deltasubsidence_length)/sum(data$length)),(sum(data$deltasubsidence_pop)/sum(data$pop_below_10p0)),(sum(data$citysubsidence_uncontrolled_high_length)/sum(data$length)),(sum(data$citysubsidence_uncontrolled_high_pop)/sum(data$pop_below_10p0)),(sum(data$citysubsidence_uncontrolled_low_length)/sum(data$length)),(sum(data$citysubsidence_uncontrolled_low_pop)/sum(data$pop_below_10p0))))
)

colnames(table1) <- c("satellite - length","satellite - pop","uplift - length","uplift - pop","delta - length","delta - pop","city (high) - length","city (high) - pop","city (low) - length","city (low) - pop")
write.csv(table1,"table1.csv",row.names=F)
